name: Run Tests 
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps: 
      - name: Get code
        uses: actions/checkout@v3
        # with: 
        #   node-verson: '18'
      - name: Install dependencies
        run: npm ci
      - name: Run My Tests
        run: npm test

